import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 로그인된 유저정보고 남는다, 변수에 담아서 출력해보면 증명된다
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          <Link href='/'>홈</Link>
          <Link href='/write'>글쓰기</Link>
          <Link href='/register'> 회원가입</Link>
          {
            session
              ? <span> {session.user.name} <LogoutBtn /></span>
              : <LoginBtn />
          }
        </div>
        {children}
      </body>
    </html>
  );
}
